// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mozi.Models;

#nullable disable

namespace Mozi.Migrations
{
    [DbContext(typeof(FilmContext))]
    partial class FilmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mozi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Hossz")
                        .HasColumnType("int");

                    b.Property<int>("KiadasiEv")
                        .HasColumnType("int");

                    b.Property<int>("KiadoId")
                        .HasColumnType("int");

                    b.Property<byte>("Korhatar")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("KiadoId");

                    b.ToTable("filmek");
                });

            modelBuilder.Entity("Mozi.Models.FilmMufaj", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<int>("MufajId")
                        .HasColumnType("int");

                    b.HasKey("FilmId", "MufajId");

                    b.HasIndex("MufajId");

                    b.ToTable("FilmMufaj");
                });

            modelBuilder.Entity("Mozi.Models.Kiado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KiadoNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("kidadok");
                });

            modelBuilder.Entity("Mozi.Models.Mufaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("MufajNev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("mufajok");
                });

            modelBuilder.Entity("Mozi.Models.Film", b =>
                {
                    b.HasOne("Mozi.Models.Kiado", "Kiado")
                        .WithMany()
                        .HasForeignKey("KiadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kiado");
                });

            modelBuilder.Entity("Mozi.Models.FilmMufaj", b =>
                {
                    b.HasOne("Mozi.Models.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mozi.Models.Mufaj", "Mufaj")
                        .WithMany()
                        .HasForeignKey("MufajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Mufaj");
                });

            modelBuilder.Entity("Mozi.Models.Mufaj", b =>
                {
                    b.HasOne("Mozi.Models.Film", null)
                        .WithMany("Mufajok")
                        .HasForeignKey("FilmId");
                });

            modelBuilder.Entity("Mozi.Models.Film", b =>
                {
                    b.Navigation("Mufajok");
                });
#pragma warning restore 612, 618
        }
    }
}
