// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tanulok.Models;

#nullable disable

namespace tanulok.Migrations
{
    [DbContext(typeof(TanuloContext))]
    [Migration("20260928115644_fejlesztesek")]
    partial class fejlesztesek
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("tanulok.Models.Tanulo", b =>
                {
                    b.Property<int>("azon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("azon"));

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("elozoIskola")
                        .HasColumnType("longtext");

                    b.Property<bool>("kituno")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("KitunoTanulo");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("azon");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
